name: Build App

# Only pushes and PRs against the main branch are built
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: 'true'

    - uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 17

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Build APKs
      run: ./gradlew :app:assembleDebug :app:testDebug :ktlintCheck :app:koverHtmlReportDebug
